name: Publish Python Package

on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install build and twine
        pip install build twine

###########################
    - name: Verify setup.py version
      run: |
        # Navigate to the package root directory where setup.py is located
        cd lean-kg
        # Use Python to read the version from setup.py and print it
        python -c "import setuptools; setup_args = {}; exec(open('setup.py').read(), {'setup': lambda **kw: setup_args.update(kw)}); print(f'Version from setup.py: {setup_args.get(\'version\')}')"

    - name: Build package
      run: python -m build
###########################
      
    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} 
      run: twine upload --repository testpypi dist/* --verbose
      # run: twine upload dist/*
